"""initial schema

Revision ID: 71628be6a322
Revises: 
Create Date: 2026-07-13 12:10:08.958587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71628be6a322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_price_stock_date')
    )
    op.create_table('fundamentals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_period', sa.String(length=20), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pat', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capital_employed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cfo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'report_date', 'period_type', name='uq_fund_stock_date_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundamentals')
    op.drop_table('daily_prices')
    op.drop_table('stocks')
    # ### end Alembic commands ###
